### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by CyberLykan** [s1dlx/sd-webui-bayesian-merger#1]
I tried merging AOM3A2 and 7th_anime_v3_C.

```
(venv) D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger>python bayesian_merger.py --model_a "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors" --model_b "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors"
You do not have an aesthetic model ckpt, let me download that for you
saved into D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\models\sac+logos+ava1-l14-linearMSE.pth
Loading aestetic scorer model
Loading CLIP
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors
merging 1/2: 100%|████████████████████████████████████████████████████████████████| 1133/1133 [00:06<00:00, 168.10it/s]
merging 2/2: 100%|█████████████████████████████████████████████████████████████████████████| 1131/1131 [00:00<?, ?it/s]
Saving D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\bbwm-AOM3A2-7th_anime_v3_C.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors
merging 1/2: 100%|████████████████████████████████████████████████████████████████| 1133/1133 [00:06<00:00, 171.05it/s]
merging 2/2: 100%|█████████████████████████████████████████████████████████████████████████| 1131/1131 [00:00<?, ?it/s]
Saving D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\bbwm-AOM3A2-7th_anime_v3_C.safetensors
Iteration 0:
        {'target': 5.574148654937744, 'params': {'base_alpha': 0.417022004702574, 'block_0': 0.7203244934421581, 'block_1': 0.00011437481734488664, 'block_10': 0.30233257263183977, 'block_11': 0.14675589081711304, 'block_12': 0.0923385947687978, 'block_13': 0.1862602113776709, 'block_14': 0.34556072704304774, 'block_15': 0.39676747423066994, 'block_16': 0.538816734003357, 'block_17': 0.4191945144032948, 'block_18': 0.6852195003967595, 'block_19': 0.20445224973151743, 'block_2': 0.8781174363909454, 'block_20': 0.027387593197926163, 'block_21': 0.6704675101784022, 'block_22': 0.41730480236712697, 'block_23': 0.5586898284457517, 'block_24': 0.14038693859523377, 'block_3': 0.1981014890848788, 'block_4': 0.8007445686755367, 'block_5': 0.9682615757193975, 'block_6': 0.31342417815924284, 'block_7': 0.6923226156693141, 'block_8': 0.8763891522960383, 'block_9': 0.8946066635038473}}
Iteration 1:
        {'target': 5.229241847991943, 'params': {'base_alpha': 0.0, 'block_0': 0.0, 'block_1': 1.0, 'block_10': 1.0, 'block_11': 1.0, 'block_12': 1.0, 'block_13': 1.0, 'block_14': 1.0, 'block_15': 1.0, 'block_16': 0.0, 'block_17': 1.0, 'block_18': 0.0, 'block_19': 1.0, 'block_2': 0.0, 'block_20': 1.0, 'block_21': 0.0, 'block_22': 1.0, 'block_23': 0.0, 'block_24': 1.0, 'block_3': 1.0, 'block_4': 0.0, 'block_5': 0.0, 'block_6': 0.0, 'block_7': 0.0, 'block_8': 0.0, 'block_9': 1.0}}
{'target': 5.574148654937744, 'params': {'base_alpha': 0.417022004702574, 'block_0': 0.7203244934421581, 'block_1': 0.00011437481734488664, 'block_10': 0.30233257263183977, 'block_11': 0.14675589081711304, 'block_12': 0.0923385947687978, 'block_13': 0.1862602113776709, 'block_14': 0.34556072704304774, 'block_15': 0.39676747423066994, 'block_16': 0.538816734003357, 'block_17': 0.4191945144032948, 'block_18': 0.6852195003967595, 'block_19': 0.20445224973151743, 'block_2': 0.8781174363909454, 'block_20': 0.027387593197926163, 'block_21': 0.6704675101784022, 'block_22': 0.41730480236712697, 'block_23': 0.5586898284457517, 'block_24': 0.14038693859523377, 'block_3': 0.1981014890848788, 'block_4': 0.8007445686755367, 'block_5': 0.9682615757193975, 'block_6': 0.31342417815924284, 'block_7': 0.6923226156693141, 'block_8': 0.8763891522960383, 'block_9': 0.8946066635038473}}
Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 68, in <module>
    main()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 64, in main
    bo.postprocess()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 100, in postprocess
    plot(self.optimizer.res, figname=img_path)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 135, in plot
    plt.plot(scores)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\matplotlib\pyplot.py", line 2785, in plot
    return gca().plot(
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\matplotlib\axes\_axes.py", line 1688, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\matplotlib\axes\_base.py", line 311, in __call__
    yield from self._plot_args(
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\matplotlib\axes\_base.py", line 501, in _plot_args
    self.axes.yaxis.update_units(y)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\matplotlib\axis.py", line 1670, in update_units
    default = self.converter.default_units(data, self)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\matplotlib\category.py", line 105, in default_units
    axis.set_units(UnitData(data))
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\matplotlib\category.py", line 181, in __init__
    self.update(data)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\matplotlib\category.py", line 214, in update
    for val in OrderedDict.fromkeys(data):
TypeError: unhashable type: 'dict'
```

**Comment by s1dlx** [comment]
Should be fixed (on my phone, can’t test until next week 😅)

**Comment by CyberLykan** [comment]
Now I get this error.

```
(venv) D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger>python bayesian_merger.py --model_a "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors" --model_b "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors"
Loading aestetic scorer model
Loading CLIP
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors
merging 1/2: 100%|████████████████████████████████████████████████████████████████| 1133/1133 [00:05<00:00, 193.36it/s]
merging 2/2: 100%|█████████████████████████████████████████████████████████████████████████| 1131/1131 [00:00<?, ?it/s]
Saving D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\bbwm-AOM3A2-7th_anime_v3_C.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors
merging 1/2: 100%|████████████████████████████████████████████████████████████████| 1133/1133 [00:05<00:00, 189.17it/s]
merging 2/2: 100%|█████████████████████████████████████████████████████████████████████████| 1131/1131 [00:00<?, ?it/s]
Saving D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\bbwm-AOM3A2-7th_anime_v3_C.safetensors
Iteration 0:
        {'target': 5.361548900604248, 'params': {'base_alpha': 0.417022004702574, 'block_0': 0.7203244934421581, 'block_1': 0.00011437481734488664, 'block_10': 0.30233257263183977, 'block_11': 0.14675589081711304, 'block_12': 0.0923385947687978, 'block_13': 0.1862602113776709, 'block_14': 0.34556072704304774, 'block_15': 0.39676747423066994, 'block_16': 0.538816734003357, 'block_17': 0.4191945144032948, 'block_18': 0.6852195003967595, 'block_19': 0.20445224973151743, 'block_2': 0.8781174363909454, 'block_20': 0.027387593197926163, 'block_21': 0.6704675101784022, 'block_22': 0.41730480236712697, 'block_23': 0.5586898284457517, 'block_24': 0.14038693859523377, 'block_3': 0.1981014890848788, 'block_4': 0.8007445686755367, 'block_5': 0.9682615757193975, 'block_6': 0.31342417815924284, 'block_7': 0.6923226156693141, 'block_8': 0.8763891522960383, 'block_9': 0.8946066635038473}}
Iteration 1:
        {'target': 5.258429527282715, 'params': {'base_alpha': 0.0, 'block_0': 0.0, 'block_1': 1.0, 'block_10': 1.0, 'block_11': 1.0, 'block_12': 1.0, 'block_13': 1.0, 'block_14': 1.0, 'block_15': 1.0, 'block_16': 0.0, 'block_17': 1.0, 'block_18': 0.0, 'block_19': 1.0, 'block_2': 0.0, 'block_20': 1.0, 'block_21': 0.0, 'block_22': 1.0, 'block_23': 0.0, 'block_24': 1.0, 'block_3': 1.0, 'block_4': 0.0, 'block_5': 0.0, 'block_6': 0.0, 'block_7': 0.0, 'block_8': 0.0, 'block_9': 1.0}}
{'target': 5.361548900604248, 'params': {'base_alpha': 0.417022004702574, 'block_0': 0.7203244934421581, 'block_1': 0.00011437481734488664, 'block_10': 0.30233257263183977, 'block_11': 0.14675589081711304, 'block_12': 0.0923385947687978, 'block_13': 0.1862602113776709, 'block_14': 0.34556072704304774, 'block_15': 0.39676747423066994, 'block_16': 0.538816734003357, 'block_17': 0.4191945144032948, 'block_18': 0.6852195003967595, 'block_19': 0.20445224973151743, 'block_2': 0.8781174363909454, 'block_20': 0.027387593197926163, 'block_21': 0.6704675101784022, 'block_22': 0.41730480236712697, 'block_23': 0.5586898284457517, 'block_24': 0.14038693859523377, 'block_3': 0.1981014890848788, 'block_4': 0.8007445686755367, 'block_5': 0.9682615757193975, 'block_6': 0.31342417815924284, 'block_7': 0.6923226156693141, 'block_8': 0.8763891522960383, 'block_9': 0.8946066635038473}}
Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 68, in <module>
    main()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 64, in main
    bo.postprocess()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 100, in postprocess
    plot(self.optimizer.res.values(), figname=img_path)
AttributeError: 'list' object has no attribute 'values'
```

**Comment by s1dlx** [comment]
Lol ok, need to take a proper look at it

**Comment by s1dlx** [comment]
@CyberLykan should be properly fixed now

**Comment by CyberLykan** [comment]
It seems to work now. I don't see any issues here.
```
(venv) D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger>python bayesian_merger.py --model_a "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors" --model_b "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors"
Loading aestetic scorer model
Loading CLIP
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors
merging 1/2: 100%|█████████████████████████████████████████████████████████████████| 1133/1133 [00:43<00:00, 26.11it/s]
merging 2/2: 100%|█████████████████████████████████████████████████████████████████████████| 1131/1131 [00:00<?, ?it/s]
Saving D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\bbwm-AOM3A2-7th_anime_v3_C.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors
merging 1/2: 100%|████████████████████████████████████████████████████████████████| 1133/1133 [00:05<00:00, 190.74it/s]
merging 2/2: 100%|█████████████████████████████████████████████████████████████████████████| 1131/1131 [00:00<?, ?it/s]
Saving D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\bbwm-AOM3A2-7th_anime_v3_C.safetensors
Iteration 0:
        {'target': 5.815051555633545, 'params': {'base_alpha': 0.417022004702574, 'block_0': 0.7203244934421581, 'block_1': 0.00011437481734488664, 'block_10': 0.30233257263183977, 'block_11': 0.14675589081711304, 'block_12': 0.0923385947687978, 'block_13': 0.1862602113776709, 'block_14': 0.34556072704304774, 'block_15': 0.39676747423066994, 'block_16': 0.538816734003357, 'block_17': 0.4191945144032948, 'block_18': 0.6852195003967595, 'block_19': 0.20445224973151743, 'block_2': 0.8781174363909454, 'block_20': 0.027387593197926163, 'block_21': 0.6704675101784022, 'block_22': 0.41730480236712697, 'block_23': 0.5586898284457517, 'block_24': 0.14038693859523377, 'block_3': 0.1981014890848788, 'block_4': 0.8007445686755367, 'block_5': 0.9682615757193975, 'block_6': 0.31342417815924284, 'block_7': 0.6923226156693141, 'block_8': 0.8763891522960383, 'block_9': 0.8946066635038473}}
Iteration 1:
        {'target': 5.085648059844971, 'params': {'base_alpha': 0.0, 'block_0': 0.0, 'block_1': 1.0, 'block_10': 1.0, 'block_11': 1.0, 'block_12': 1.0, 'block_13': 1.0, 'block_14': 1.0, 'block_15': 1.0, 'block_16': 0.0, 'block_17': 1.0, 'block_18': 0.0, 'block_19': 1.0, 'block_2': 0.0, 'block_20': 1.0, 'block_21': 0.0, 'block_22': 1.0, 'block_23': 0.0, 'block_24': 1.0, 'block_3': 1.0, 'block_4': 0.0, 'block_5': 0.0, 'block_6': 0.0, 'block_7': 0.0, 'block_8': 0.0, 'block_9': 1.0}}
{'target': 5.815051555633545, 'params': {'base_alpha': 0.417022004702574, 'block_0': 0.7203244934421581, 'block_1': 0.00011437481734488664, 'block_10': 0.30233257263183977, 'block_11': 0.14675589081711304, 'block_12': 0.0923385947687978, 'block_13': 0.1862602113776709, 'block_14': 0.34556072704304774, 'block_15': 0.39676747423066994, 'block_16': 0.538816734003357, 'block_17': 0.4191945144032948, 'block_18': 0.6852195003967595, 'block_19': 0.20445224973151743, 'block_2': 0.8781174363909454, 'block_20': 0.027387593197926163, 'block_21': 0.6704675101784022, 'block_22': 0.41730480236712697, 'block_23': 0.5586898284457517, 'block_24': 0.14038693859523377, 'block_3': 0.1981014890848788, 'block_4': 0.8007445686755367, 'block_5': 0.9682615757193975, 'block_6': 0.31342417815924284, 'block_7': 0.6923226156693141, 'block_8': 0.8763891522960383, 'block_9': 0.8946066635038473}}
```
