### ISSUE TITLE
[BUG] stderr: ERROR: You must give at least one requirement to install

### ISSUE THREAD

**Issue by Enferlain** [s1dlx/sd-webui-bayesian-merger#105]
```
*** Error running install.py for extension /content/drive/.shortcut-targets-by-id/13MbDup-6T8zcgdjaduULg-tVnqQJ0cjq/sd24/stable-diffusion-webui/extensions/sd-webui-bayesian-merger.
*** Command: "/usr/bin/python3" "/content/drive/.shortcut-targets-by-id/13MbDup-6T8zcgdjaduULg-tVnqQJ0cjq/sd24/stable-diffusion-webui/extensions/sd-webui-bayesian-merger/install.py"
*** Error code: 1
*** stdout: Installing None
*** Installing None
*** Installing None
*** 
*** stderr: Traceback (most recent call last):
***   File "/content/drive/.shortcut-targets-by-id/13MbDup-6T8zcgdjaduULg-tVnqQJ0cjq/sd24/stable-diffusion-webui/extensions/sd-webui-bayesian-merger/install.py", line 10, in <module>
***     launch.run_pip(f"install {req}")
***   File "/content/drive/.shortcut-targets-by-id/13MbDup-6T8zcgdjaduULg-tVnqQJ0cjq/sd24/stable-diffusion-webui/modules/launch_utils.py", line 136, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "/content/drive/.shortcut-targets-by-id/13MbDup-6T8zcgdjaduULg-tVnqQJ0cjq/sd24/stable-diffusion-webui/modules/launch_utils.py", line 113, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install None.
*** Command: "/usr/bin/python3" -m pip install  --prefer-binary
*** Error code: 1
*** stderr: ERROR: You must give at least one requirement to install (see "pip help install")
```

I installed it through the extensions tab, and on next start I got this. Is there anything I can do?

**Comment by Enferlain** [comment]
Yeah no more of that error.

But now this is in the console during startup

```
['open_clip_torch\n', 'clip\n', 'Pillow\n', 'PyYAML\n', 'safetensors\n', 'torch\n', 'tqdm\n', 'bayesian-optimization\n', 'matplotlib\n', 'seaborn\n', 'hyperopt\n', 'pytest\n', 'transformers\n', 'numpy\n', 'hydra-core\n', 'sd-meh==0.9.4\n', 'lightgbm \n', 'scikit-learn\n', 'openai-clip\n']
Installing None
Installing None
Installing None
Installing None
Installing None
Installing None
Installing None
Installing None
```

and I can't see the tab for the extension

**Comment by s1dlx** [comment]
There’s no tab for this extension, it’s a cli tool
