### ISSUE TITLE
Can't find model

### ISSUE THREAD

**Issue by saftle** [s1dlx/sd-webui-bayesian-merger#17]
I'm still getting the error:

```
(venv) D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger>python bayesian_merger.py --url http://127.0.0.1:7861 --init_points 10 --batch_size 10 --model_a D:\stable-diffusion-webui\models\Stable-diffusion\URPM\URPMv1.3.safetensors --model_b D:\stable-diffusion-webui\models\Stable-diffusion\tests\cunnibsuc_05_epoch20-pruned.ckpt --payloads_dir D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\payloads --scorer_model_dir D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\models
Loading aestetic scorer model
Loading CLIP

---------- warmup ---------->

warmup - Iteration: 1
loading: D:\stable-diffusion-webui\models\Stable-diffusion\URPM\URPMv1.3.safetensors
loading: D:\stable-diffusion-webui\models\Stable-diffusion\tests\cunnibsuc_05_epoch20-pruned.ckpt
merging 1/2: 100%|████████████████████████████████████████████████████████████████| 1133/1133 [00:04<00:00, 255.76it/s]
merging 2/2: 100%|█████████████████████████████████████████████████████████████████████████| 1143/1143 [00:00<?, ?it/s]
Saving D:\stable-diffusion-webui\models\Stable-diffusion\URPM\bbwm-URPMv1.3-cunnibsuc_05_epoch20-pruned-it_1.safetensors
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 98, in <module>
    main()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 93, in main
    bo.optimise()
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 112, in optimise
    self.optimizer.maximize(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\bayes_opt\bayesian_optimization.py", line 311, in maximize
    self.probe(x_probe, lazy=False)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\bayes_opt\bayesian_optimization.py", line 208, in probe
    self._space.probe(params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\bayes_opt\target_space.py", line 236, in probe
    target = self.target_func(**params)
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 79, in sd_target_function
    self.generator.switch_model(self.merger.model_out_name)
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 34, in switch_model
    title = self.find_title(Path(ckpt).stem)
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 64, in find_title
    raise ValueError(f"model {model_name} not found")
ValueError: model bbwm-URPMv1.3-cunnibsuc_05_epoch20-pruned-it_1 not found
```

_Originally posted by @saftle in https://github.com/s1dlx/sd-webui-bayesian-merger/issues/3#issuecomment-1474881731_

**Comment by saftle** [comment]
I've tried converting them both to safetensors, both to CKPT, and also tried putting them both in the same folder. All without success sadly.

**Comment by s1dlx** [comment]
The merged model should be saved in the same folder containing model_a. Can you check whether it’s there?

there may be some writing permissions the script doesn’t have, not sure how windows handle those

**Comment by saftle** [comment]
@s1dlx it actually does get merged and shows up in the right directory, however it still shows that error.

**Comment by s1dlx** [comment]
@saftle puzzling...

would this help?
https://github.com/s1dlx/sd-webui-bayesian-merger/issues/18#issuecomment-1475982059

**Comment by s1dlx** [comment]
it turns out that in some (not really clear to me) cases, the webui api call fails to refresh models list when there are multiple files in the `models/Stable-diffusion/` folder

the fix was to move all the models in a subfolder (webui will still find them) and leave only the two models you want to merge in the base directory
