### ISSUE TITLE
No connection adapters were found for sdapi/v1/refresh-checkpoints

### ISSUE THREAD

**Issue by gitboomer** [s1dlx/sd-webui-bayesian-merger#18]
Python 3.10.6
WebUI updated

Bayesian merger completes the first merge, saves the merged model, then fails to refresh checkpoints between the second merge.

```
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 98, in <module>
    main()
  File "C:\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 93, in main
    bo.optimise()
  File "C:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 112, in optimise
    self.optimizer.maximize(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\bayes_opt\bayesian_optimization.py", line 311, in maximize
    self.probe(x_probe, lazy=False)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\bayes_opt\bayesian_optimization.py", line 208, in probe
    self._space.probe(params)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\bayes_opt\target_space.py", line 236, in probe
    target = self.target_func(**params)
  File "C:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 79, in sd_target_function
    self.generator.switch_model(self.merger.model_out_name)
  File "C:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 33, in switch_model
    self.refresh_models()
  File "C:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 48, in refresh_models
    r = requests.post(url=f"{self.url}/sdapi/v1/refresh-checkpoints")
  File "C:\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '127.0.0.1:7861/sdapi/v1/refresh-checkpoints'
```

**Comment by s1dlx** [comment]
this is a new one...

just to check, I'm running webui with the following flags
```
--share --api --enable-insecure-extension-access --nowebui
```

I'd say both `--share` and `--enable-insecure-extension-access` are not needed, but can you give it a go?

also, I'm still using an old webui version, I'm on `eafaf141` commit. Try also to revert to that. I'm afraid the error you're getting is because of some recent change in their codebase

**Comment by gitboomer** [comment]
I approached this a few different ways. Both on my existing install and after a fresh install.

First with _just_ the updated COMMANDLINE_ARGS
Then with _just_ eafaf141 VIA git checkout
Then with eafaf141 VIA git checkout eafaf141 and updated COMMANDLINE_ARGS
Then with _just_ git reset --hard eafaf14167cf574ad0f918c10f60ef86aea9cd20
Then with git reset --hard eafaf14167cf574ad0f918c10f60ef86aea9cd20 and updated COMMANDLINE_ARGS

Unfortunately the issue persists.

**Comment by s1dlx** [comment]
@gitboomer can you try to run this simple script? launch webui with `--api` arg, that should be enough. Also, fill in `url` with the right one

```python
import requests

url = ""
r = requests.post(url=f"{url}/sdapi/v1/refresh-checkpoints")
r.raise_for_status()
```

**Comment by s1dlx** [comment]
@gitboomer have a look at this
https://stackoverflow.com/questions/15115328/python-requests-no-connection-adapters

Can you double check the url you are using?

**Comment by gitboomer** [comment]
```
import requests

url = "http://127.0.0.1:7860"
r = requests.post(url=f"{url}/sdapi/v1/refresh-checkpoints")
r.raise_for_status()
```

**Comment by s1dlx** [comment]
yep that's good

now when you launch the script, make sure you set `--url http://127.0.0.1:7860` if running webui with `--api` flag only

In case you run with `--nowebui` too, use instead `--url http://127.0.0.1:7861`
