### ISSUE TITLE
Unable to find safetensors model.

### ISSUE THREAD

**Issue by CyberLykan** [s1dlx/sd-webui-bayesian-merger#3]
The model does get created and saved in the models folder though. Looks like the code is only looking for ckpt and not safetensors as well.
```
(venv) D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger>python bayesian_merger.py --init_points 10 --n_iters 10 --batch_size 10 --model_a "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors" --model_b "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors" --skip_position_ids 2
You do not have an aesthetic model ckpt, let me download that for you
saved into D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\models\sac+logos+ava1-l14-linearMSE.pth
Loading aestetic scorer model
Loading CLIP
Iteration: 1
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors
loading: D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors
merging 1/2: 100%|█████████████████████████████████████████████████████████████████| 1133/1133 [01:07<00:00, 16.82it/s]
merging 2/2: 100%|█████████████████████████████████████████████████████████████████████████| 1131/1131 [00:00<?, ?it/s]
Saving D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\bbwm-AOM3A2-7th_anime_v3_C-1.safetensors
Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 98, in <module>
    main()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 93, in main
    bo.optimise()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 98, in optimise
    self.optimizer.maximize(
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\bayes_opt\bayesian_optimization.py", line 311, in maximize
    self.probe(x_probe, lazy=False)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\bayes_opt\bayesian_optimization.py", line 208, in probe
    self._space.probe(params)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\bayes_opt\target_space.py", line 236, in probe
    target = self.target_func(**params)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 71, in sd_target_function
    self.generator.switch_model(self.merger.model_out_name)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 33, in switch_model
    prev_title = self.find_title(Path(ckpt).stem)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 69, in find_title
    raise ValueError(f"model {model_name} not found")
ValueError: model bbwm-AOM3A2-7th_anime_v3_C-1 not found
```

**Comment by s1dlx** [comment]
@CyberLykan yeah, the api for reloading a checkpoint is not working as I expected to...

basically if the filename doesn't change (but the actual checkpoint is different), refreshing and re-loading simply uses the cached model.

I pushed a fix in [7323868](https://github.com/s1dlx/sd-webui-bayesian-merger/commit/732386880f2c2554a0d06cf9388189157f40b808)
now it should work fine, even though it's not the best solution

**Comment by CyberLykan** [comment]
Seems to work right now.

**Comment by saftle** [comment]
I'm still getting the error:

```
(venv) D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger>python bayesian_merger.py --url http://127.0.0.1:7861 --init_points 10 --batch_size 10 --model_a D:\stable-diffusion-webui\models\Stable-diffusion\URPM\URPMv1.3.safetensors --model_b D:\stable-diffusion-webui\models\Stable-diffusion\tests\cunnibsuc_05_epoch20-pruned.ckpt --payloads_dir D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\payloads --scorer_model_dir D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\models
Loading aestetic scorer model
Loading CLIP

---------- warmup ---------->

warmup - Iteration: 1
loading: D:\stable-diffusion-webui\models\Stable-diffusion\URPM\URPMv1.3.safetensors
loading: D:\stable-diffusion-webui\models\Stable-diffusion\tests\cunnibsuc_05_epoch20-pruned.ckpt
merging 1/2: 100%|████████████████████████████████████████████████████████████████| 1133/1133 [00:04<00:00, 255.76it/s]
merging 2/2: 100%|█████████████████████████████████████████████████████████████████████████| 1143/1143 [00:00<?, ?it/s]
Saving D:\stable-diffusion-webui\models\Stable-diffusion\URPM\bbwm-URPMv1.3-cunnibsuc_05_epoch20-pruned-it_1.safetensors
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 98, in <module>
    main()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 93, in main
    bo.optimise()
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 112, in optimise
    self.optimizer.maximize(
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\bayes_opt\bayesian_optimization.py", line 311, in maximize
    self.probe(x_probe, lazy=False)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\bayes_opt\bayesian_optimization.py", line 208, in probe
    self._space.probe(params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\bayes_opt\target_space.py", line 236, in probe
    target = self.target_func(**params)
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 79, in sd_target_function
    self.generator.switch_model(self.merger.model_out_name)
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 34, in switch_model
    title = self.find_title(Path(ckpt).stem)
  File "D:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 64, in find_title
    raise ValueError(f"model {model_name} not found")
ValueError: model bbwm-URPMv1.3-cunnibsuc_05_epoch20-pruned-it_1 not found
```
