### ISSUE TITLE
Escaped characters do not work in prompts.

### ISSUE THREAD

**Issue by CyberLykan** [s1dlx/sd-webui-bayesian-merger#4]
Such as in `shrug \(clothing\)`
```
(venv) D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger>python bayesian_merger.py --init_points 10 --n_iters 10 --batch_size 10 --model_a "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\AOM3A2.safetensors" --model_b "D:\My Stuff\Extra Stuff\stable-diffusion-webui\models\Stable-diffusion\7th_anime_v3_C.safetensors" --skip_position_ids 2
Loading aestetic scorer model
Loading CLIP
Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 98, in <module>
    main()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 92, in main
    bo = BayesianOptimiser(*args, **kwargs)
  File "<string>", line 14, in __init__
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 49, in __post_init__
    self.prompter = Prompter(self.payloads_dir, self.wildcards_dir)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\prompter.py", line 83, in __init__
    self.load_payloads()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\prompter.py", line 102, in load_payloads
    raw_payload = load_yaml(payload["path"])
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\prompter.py", line 45, in load_yaml
    return yaml.safe_load(f)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\scanner.py", line 1152, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\yaml\scanner.py", line 1223, in scan_flow_scalar_non_spaces
    raise ScannerError("while scanning a double-quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\payloads\aki_rosenthal.yaml", line 1, column 9
found unknown escape character '('
  in "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\payloads\aki_rosenthal.yaml", line 1, column 276
```

**Comment by s1dlx** [comment]
interesting...

what's the purpose of escaping brackets?

**Comment by CyberLykan** [comment]
Certain tags have parentheses to differentiate from others with the same name. Perhaps to indicate it as a clothing item `shrug \(clothing\)` or for different variants `artoria_pendragon_(fate)` `artoria_pendragon_(lancer)_(fate)` `artoria_pendragon_(lancer_alter)_(fate)`

Escaping these parenthesis ensure that they don't get read as prompt weighting, so `artoria_pendragon_(fate)` doesn't become `artoria_pendragon, (fate)`

**Comment by s1dlx** [comment]
I see, thanks for explaining, I wasn’t aware of it

it may be because of the yaml library I’m using, I’ll do some tests to fix this

**Comment by CyberLykan** [comment]
Maybe doing `shrug \\(clothing\\)` might work? Escape the slashes.

**Comment by CyberLykan** [comment]
Can confirm escaping the backslashes work.

**Comment by s1dlx** [comment]
@CyberLykan 
I had a look and `\\( something \\)` doesn't raise that error

that should render as `\( something \)` which in turn is parsed as `( something )` by webui literally (not weighting that to 1.1)
