### ISSUE TITLE
AttributeError: module 'clip' has no attribute 'load'

### ISSUE THREAD

**Issue by hoblin** [s1dlx/sd-webui-bayesian-merger#55]
Running on Windows. Got an exception.

```
$ python bayesian_merger.py
Loading sac+logos+ava1-l14-linearMSE.pth
Loading ViT-L/14
Error executing job with overrides: []
Traceback (most recent call last):
  File "D:\WebUI\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 37, in main
    bo = cls(cfg)
  File "<string>", line 5, in __init__
  File "D:\WebUI\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 127, in __post_init__
    self.scorer = AestheticScorer(self.cfg)
  File "<string>", line 4, in __init__
  File "D:\WebUI\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\scorer.py", line 77, in __post_init__
    self.load_model()
  File "D:\WebUI\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\scorer.py", line 136, in load_model
    self.load_clip()
  File "D:\WebUI\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\scorer.py", line 147, in load_clip
    self.clip_model, self.clip_preprocess = clip.load(
AttributeError: module 'clip' has no attribute 'load'
```

**Comment by hoblin** [comment]
ok, i downloaded a better shell for windows, removed couple weirdly looking packages from the venv directory, installed requirements once again and now it just works.
