### ISSUE TITLE
Error after latest update

### ISSUE THREAD

**Issue by unfusion** [s1dlx/sd-webui-bayesian-merger#56]
First of all, thank you for the useful program.
An error occurred during the merge attempt after the recent update.

> warmup - Iteration: 1
> loading: F:\MergerWebUI\repo\models\Stable-diffusion\some.safetensors
> loading: F:\MergerWebUI\repo\models\Stable-diffusion\some2.safetensors
> stage 1: 100%|████████████████████████████| 1143/1143 [00:05<00:00, 214.88it/s]
> stage 2: 100%|█████████████████████████████████████| 1130/1130 [00:00<?, ?it/s]
> Saving F:\MergerWebUI\repo\models\Stable-diffusion\bbwm-some-some2-it_1.safetensors
> Loading model: bbwm-some-some2-it_1.safetensors
> Error executing job with overrides: []
> Traceback (most recent call last):
>   File "F:\MergerWebUI\repo\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 38, in main
>     bo.optimise()
>   File "F:\MergerWebUI\repo\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\bayes_optimiser.py", line 28, in optimise
>     self.optimizer.maximize(
>   File "F:\MergerWebUI\repo\venv\lib\site-packages\bayes_opt\bayesian_optimization.py", line 311, in maximize
>     self.probe(x_probe, lazy=False)
>   File "F:\MergerWebUI\repo\venv\lib\site-packages\bayes_opt\bayesian_optimization.py", line 208, in probe
>     self._space.probe(params)
>   File "F:\MergerWebUI\repo\venv\lib\site-packages\bayes_opt\target_space.py", line 236, in probe
>     target = self.target_func(**params)
>   File "F:\MergerWebUI\repo\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 209, in sd_target_function
>     images, gen_paths = self.generate_images(paths, payloads)
> NameError: name 'paths' is not defined
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

So I put the code below in line 208, and it seems to be working.

> payloads, paths = self.prompter.render_payloads()

But I'm not a professional developer, so I don't know if this is the right solution. Please check.

**Comment by unfusion** [comment]
I started another merge task, and no error message appeared. By the way, the following error message appeared on completion in the previous task, but I don't know if it's because of the syntax I modified. I will check if an error message occurs again when the new merge task finished.


```
Error executing job with overrides: []
Traceback (most recent call last):
  File "F:\MergerWebUI\repo\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 43, in <module>
    main()
  File "F:\MergerWebUI\repo\venv\lib\site-packages\hydra\main.py", line 94, in decorated_main
    _run_hydra(
  File "F:\MergerWebUI\repo\venv\lib\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "F:\MergerWebUI\repo\venv\lib\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "F:\MergerWebUI\repo\venv\lib\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "F:\MergerWebUI\repo\venv\lib\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
  File "F:\MergerWebUI\repo\venv\lib\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "F:\MergerWebUI\repo\venv\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "F:\MergerWebUI\repo\venv\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "F:\MergerWebUI\repo\venv\lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "F:\MergerWebUI\repo\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 39, in main
    bo.postprocess()
  File "F:\MergerWebUI\repo\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\bayes_optimiser.py", line 45, in postprocess
    best_bases, best_weights = self.parse_params(
  File "F:\MergerWebUI\repo\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\bayes_optimiser.py", line 57, in parse_params
    bases = {"alpha": params["base_alpha"]}
KeyError: 'base_alpha'
``` 

my config.yaml
```
defaults:
  - _self_
  - payloads: cargo
  - optimisation_guide: guide

run_name: ${optimiser}_${scorer_method}
hydra:
  run:
    dir: logs/${now:%Y-%m-%d_%H-%M-%S}_${run_name}

url: http://127.0.0.1:7860
device: cpu

wildcards_dir: F:\MergerWebUI\repo\extensions\sd-webui-bayesian-merger\wildcards
scorer_model_dir: F:\MergerWebUI\repo\extensions\sd-webui-bayesian-merger\models

model_a: F:\MergerWebUI\repo\models\Stable-diffusion\some.safetensors
model_b: F:\MergerWebUI\repo\models\Stable-diffusion\some2.safetensors
skip_position_ids: 0
merge_mode: weighted_sum  # weighted_sum (default), add_difference, sum_twice, triple_sum

optimiser: bayes            # tpe
bounds_transformer: True    # bayes only
guided_optimisation: false
batch_size: 10
init_points: 10
n_iters: 10

save_imgs: True

scorer_method: chad # laion, aes, cafe_aesthetic, cafe_style, cafe_waifu
scorer_model_name: sac+logos+ava1-l14-linearMSE.pth # ava+logos-l14-linearMSE.pth, ava+logos-l14-reluMSE.pth

save_best: True
best_format: safetensors # ckpt
best_precision: 32 # 32

draw_unet_weights: False
draw_unet_base_alpha: False

```

**Comment by unfusion** [comment]
Thank you. Then I'll close this issue.
