### ISSUE TITLE
[BUG] ValueError: model bbwm [Model name] not found

### ISSUE THREAD

**Issue by Ketorami** [s1dlx/sd-webui-bayesian-merger#86]
**Describe the bug**
I can't merge the models no matter what I try. It alway error. I read the Repo earlier and found the same issue, but even after following the instructions, the problem still isn't resolved.

`(venv) PS E:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger> python bayesian_merger.py
You do not have an aesthetic model ckpt, let me download that for you
saved into E:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\models\ava+logos-l14-linearMSE.pth
Loading ava+logos-l14-linearMSE.pth
Loading ViT-L/14

---------- warmup ---------->

warmup - Iteration: 1
loading: E:\stable-diffusion-webui\models\Stable-diffusion\Merge-Model\1.safetensors
loading: E:\stable-diffusion-webui\models\Stable-diffusion\Merge-Model\2.safetensors
stage 1: 100%|█████████████████████████████████████████████████████████████████████| 1131/1131 [00:15<00:00, 72.39it/s]
stage 2: 100%|████████████████████████████████████████████████████████████████| 1131/1131 [00:00<00:00, 1123314.66it/s]
Saving E:\stable-diffusion-webui\models\Stable-diffusion\Merge-Model\bbwm-1-2-it_1.safetensors
Error executing job with overrides: []
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 33, in main
    bo.optimise()
  File "E:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\bayes_optimiser.py", line 42, in optimise
    self.optimizer.maximize(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\bayes_opt\bayesian_optimization.py", line 310, in maximize
    self.probe(x_probe, lazy=False)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\bayes_opt\bayesian_optimization.py", line 208, in probe
    self._space.probe(params)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\bayes_opt\target_space.py", line 236, in probe
    target = self.target_func(**params)
  File "E:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 101, in sd_target_function
    self.generator.switch_model(self.merger.model_out_name)
  File "E:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 33, in switch_model
    title = self.find_title(Path(ckpt).stem)
  File "E:\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\generator.py", line 63, in find_title
    raise ValueError(f"model {model_name} not found")
ValueError: model bbwm-1-2-it_1 not found

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

![image](https://github.com/s1dlx/sd-webui-bayesian-merger/assets/101268214/8d0a5e46-9f8b-438a-8656-eaf9dc32d9b8)

**Comment by Ketorami** [comment]
@s1dlx 

What is meant by 'particular folder structure'? Does it refer to creating a specific folder for the model that will be used for merging?

Like this ? 

![image](https://github.com/s1dlx/sd-webui-bayesian-merger/assets/101268214/29f0eb94-5b5d-47bd-b4db-035de342e40f)

**Comment by Ketorami** [comment]
It Work !!! Thank
