### ISSUE TITLE
[BUG] ValueError: Expected a dict of [str, torch.Tensor] but received <class 'tensordict.tensordict.TensorDict'>

### ISSUE THREAD

**Issue by Derjyn** [s1dlx/sd-webui-bayesian-merger#89]
**Describe the bug**
When running script, get the following error when saving the first iteration:

`ValueError: Expected a dict of [str, torch.Tensor] but received <class 'tensordict.tensordict.TensorDict'>
`

Here is a more detailed trace:

```
Error executing job with overrides: []
Traceback (most recent call last):
  File "D:\AIA\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\bayesian_merger.py", line 33, in main
    bo.optimise()
  File "D:\AIA\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\bayes_optimiser.py", line 42, in optimise
    self.optimizer.maximize(
  File "C:\Program Files\Python310\lib\site-packages\bayes_opt\bayesian_optimization.py", line 310, in maximize
    self.probe(x_probe, lazy=False)
  File "C:\Program Files\Python310\lib\site-packages\bayes_opt\bayesian_optimization.py", line 208, in probe
    self._space.probe(params)
  File "C:\Program Files\Python310\lib\site-packages\bayes_opt\target_space.py", line 236, in probe
    target = self.target_func(**params)
  File "D:\AIA\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\optimiser.py", line 98, in sd_target_function
    self.merger.merge(weights, bases)
  File "D:\AIA\stable-diffusion-webui\extensions\sd-webui-bayesian-merger\sd_webui_bayesian_merger\merger.py", line 127, in merge
    safetensors.torch.save_file(
  File "C:\Program Files\Python310\lib\site-packages\safetensors\torch.py", line 232, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "C:\Program Files\Python310\lib\site-packages\safetensors\torch.py", line 379, in _flatten
    raise ValueError(f"Expected a dict of [str, torch.Tensor] but received {type(tensors)}")
ValueError: Expected a dict of [str, torch.Tensor] but received <class 'tensordict.tensordict.TensorDict'>
```

**To Reproduce**
1. Run script.
2. Stage 1 and Stage 2 complete.
3. On saving, script errors out.

**Expected behavior**
Task completes without error...

**Comment by Derjyn** [comment]
I hopped back a version, and this issue goes away. However also of note: we can't place models in a subdirectory within the `models/Stable-diffusion` folder.
